[package]
name = "process_explorer"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.37.2"
egui = "0.27"
eframe = { version = "0.27", default-features = false, features = ["default_fonts", "glow"] }